module.exports = {

    CREATE_USER: "CREATE_USER",

    UPDATE_USER: "UPDATE_USER",

    DELETE_USER: "DELETE_USER",

    VIEW_USER: "VIEW_USER",

    CREATE_PNR: "CREATE_PNR",

    UPDATE_PNR: "UPDATE_PNR",

    DELETE_PNR: "DELETE_PNR",

    SEAT_EXCHANGE: "SEAT_EXCHANGE",

};